// Flow Fusion site build. Zero dependencies; Node 18+.
//   src/styles.base.css + src/styles.sections.css -> dist/styles.css
//   src/site.js                                    -> dist/site.js
//   src/site.html (+ wrapper)                       -> index.html      (standalone page)
//   <style> + fragment + <script>, logo inlined     -> dist/ghl-embed.html (paste into a GHL custom-code block)
import { readFileSync, writeFileSync, existsSync, mkdirSync, statSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve, relative } from 'node:path';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const p = (...s) => resolve(ROOT, ...s);
const read = (f) => readFileSync(p(f), 'utf8');

const REAL_LOGO = 'assets/logo.png';
const PLACEHOLDER_LOGO = 'assets/logo.placeholder.png';
const LOGO_ATTR = 'src="assets/logo.png"';

const css = read('src/styles.base.css').trimEnd() + '\n\n' + read('src/styles.sections.css').trimEnd() + '\n';
const js = read('src/site.js');
const fragment = read('src/site.html').trim();

if (!fragment.includes(LOGO_ATTR)) {
  console.warn(`WARNING: src/site.html contains no ${LOGO_ATTR} - logo rewriting will be a no-op.`);
}

// Resolve which logo to use.
let logoPath = REAL_LOGO;
if (!existsSync(p(REAL_LOGO))) {
  if (!existsSync(p(PLACEHOLDER_LOGO))) {
    console.error(`ERROR: neither ${REAL_LOGO} nor ${PLACEHOLDER_LOGO} exists. Run "npm run placeholder" or add the real logo.`);
    process.exit(1);
  }
  logoPath = PLACEHOLDER_LOGO;
  console.log('');
  console.log('*** WARNING: real logo missing ***');
  console.log(`  ${REAL_LOGO} was not found. Using ${PLACEHOLDER_LOGO} instead.`);
  console.log(`  Drop the real 1904x1967 PNG at ${REAL_LOGO} and re-run "npm run build".`);
  console.log('');
}

// Inline scripts must not contain a literal "</script>".
const safeJs = js.replace(/<\/script/gi, '<\\/script');
const safeCss = css.replace(/<\/style/gi, '<\\/style');

// --- dist/styles.css and dist/site.js -----------------------------------
mkdirSync(p('dist'), { recursive: true });
writeFileSync(p('dist/styles.css'), css);
writeFileSync(p('dist/site.js'), js);

// --- index.html (standalone page) ----------------------------------------
const indexFragment = fragment.split(LOGO_ATTR).join(`src="${logoPath}"`);
const indexHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Flow Fusion — Automation made simple</title>
  <meta name="description" content="Flow Fusion keeps your contacts, conversations, and next steps connected. CRM from $99/mo, CRM + SMS plans from $150/mo.">
  <link rel="stylesheet" href="dist/styles.css">
  <style>html,body{margin:0;background:#08090b}</style>
</head>
<body>
${indexFragment}
<script src="dist/site.js" defer></script>
</body>
</html>
`;
writeFileSync(p('index.html'), indexHtml);

// --- dist/ghl-embed.html (self-contained snippet) -------------------------
const logoBytes = readFileSync(p(logoPath));
const dataUri = `data:image/png;base64,${logoBytes.toString('base64')}`;
const embedFragment = fragment.split(LOGO_ATTR).join(`src="${dataUri}"`);
const embedHtml = `<!-- Flow Fusion site — generated by scripts/build.mjs. Paste this whole block into a GoHighLevel custom-code element. -->
<style>
${safeCss.trimEnd()}
</style>
${embedFragment}
<script>
${safeJs.trimEnd()}
</script>
`;
writeFileSync(p('dist/ghl-embed.html'), embedHtml);

// --- summary ---------------------------------------------------------------
const fmt = (n) => (n >= 1024 * 1024 ? `${(n / 1024 / 1024).toFixed(2)} MB` : n >= 1024 ? `${(n / 1024).toFixed(1)} KB` : `${n} B`);
console.log(`Build complete (logo: ${logoPath})`);
for (const f of ['dist/styles.css', 'dist/site.js', 'index.html', 'dist/ghl-embed.html']) {
  console.log(`  ${relative(ROOT, p(f)).padEnd(22)} ${fmt(statSync(p(f)).size)}`);
}
